# Generated by Django 3.2.9 on 2021-12-02 02:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(max_length=32, verbose_name='Senha')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('medico', models.BooleanField(default=True, verbose_name='Medico?')),
                ('especialidade', models.CharField(blank=True, max_length=25, verbose_name='Especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(max_length=32, verbose_name='Senha')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('medico', models.BooleanField(default=True, verbose_name='Medico?')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da consulta')),
                ('Horario', models.TimeField(auto_now_add=True, verbose_name='Data da consulta')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.paciente')),
            ],
        ),
    ]
