# Generated by Django 3.2.9 on 2021-12-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='Horario',
            field=models.TimeField(blank=True, verbose_name='Data da consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(blank=True, verbose_name='Data da consulta'),
        ),
    ]
