# Generated by Django 3.2.9 on 2021-12-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20211201_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='Horario',
        ),
    ]
