# Generated by Django 3.2.9 on 2021-12-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_consulta_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='especialidade',
            field=models.CharField(blank=True, max_length=25, verbose_name='Especialidade'),
        ),
    ]
