# Generated by Django 3.2.9 on 2021-12-02 02:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_consulta_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=15, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(blank=True, max_length=32, verbose_name='Senha')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('Ehmedico', models.BooleanField(blank=True, default=False, verbose_name='Medico?')),
                ('especialidade', models.CharField(max_length=25, verbose_name='Especialidade')),
            ],
        ),
        migrations.RemoveField(
            model_name='medico',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.usuario'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.usuario'),
        ),
    ]
