# Generated by Django 3.2.9 on 2021-12-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20211201_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='especialidade',
            field=models.CharField(blank=True, max_length=25, verbose_name='Especialidade'),
        ),
    ]
